# Generated by Django 4.1.1 on 2022-10-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('last_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField(verbose_name='hire_date')),
            ],
            options={
                'db_table': 'professors',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('student_no', models.IntegerField(primary_key=True, serialize=False)),
                ('course_no', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'student_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('last_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_no', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'teach',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.section')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
    ]
