# Generated by Django 4.1.1 on 2022-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='query',
            table='queries',
        ),
    ]
